name: Run-Drake-Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  build-container:
    name: Run workflow
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build image with cache
        id: build_docker
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: $GITHUB_ACTOR
          password: "${{ secrets.GITHUB_TOKEN }}"
          registry: docker.pkg.github.com
          image_name: peskas-minderoo-report

      - name: Save Google Storage Authentication
        run: |
          mkdir auth
          echo "${{ secrets.PESKAS_DATAINGESTION_GCS_KEY }}" > auth/gcp-sa-peskas_ingestion-key.json

      - name: Run Targets workflow
        run: docker run -v $(pwd):/home -w /home --name rstudio_container ${{ steps.build_docker.outputs.FULL_IMAGE_NAME }} make

      - name: Save report as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: report-output
          path: reports/minderoo_figures.docx
